name: Translate Moda Yakamoz XML Feed

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Required to push

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Moda Yakamoz XML translation
      run: python translatexml_yakamoz.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add translatedsample_yakamoz.xml translated_ids_yakamoz.json
        git commit -m "🔄 Auto-update translated Moda Yakamoz XML [bot]" || echo "No changes to commit"
        git push

