name: Download and Process Moda Yakamoz XML

on:
  schedule:
    - cron: "0 */4 * * *"  # Every 4 hours
  workflow_dispatch:       # Manual trigger

jobs:
  download-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright deep-translator requests

    - name: Install Playwright browser
      run: playwright install chromium

    - name: Run Playwright script to download and process XML
      run: python modayakamoz_playwright.py

    - name: Run Yakamoz translation script
      run: python translatexml_yakamoz.py
