name: Download and Process Moda Yakamoz XML

on:
  schedule:
    - cron: "0 */4 * * *"  # Every 4 hours
  workflow_dispatch:       # Manual trigger

jobs:
  download-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # We'll provide token explicitly for pushing

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright deep-translator requests

    - name: Install Playwright browser
      run: playwright install chromium

    - name: Run Playwright script to download and process XML
      run: python modayakamoz_playwright.py

    - name: Run Yakamoz translation script
      run: python translatexml_yakamoz.py

    - name: Commit and push translated XML
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add translatedsample_yakamoz.xml
        git diff --cached --quiet || git commit -m "Update translatedsample_yakamoz.xml [skip ci]"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
